### ISSUE TITLE
MIDI keyboard's poblem

### ISSUE THREAD

**Issue by mattiasalvi** [cwilso/midi-synth#12]
Hi Chris,
I'm using the latest version of Chrome with the MIDI flag enabled.
I can connect your sinth with my MIDI controllers, so i can see my keyboard in the MIDI_IN list.
When I try to play with your virtual piano I can hear the sound but, if I try to play with my keyboard it doesn't sound.
Have you got any idea to risolve this problem?

Thanks!
Mattia.

**Comment by cwilso** [comment]
Please try again; I just reworked the logic.
