### ISSUE TITLE
ChromeOS requires reboot to recognize MIDI device after enable-web-midi flag

### ISSUE THREAD

**Issue by jzellis** [cwilso/midi-synth#13]
Not a bug so much as a head's up for anybody trying this with a Chromebook: it seems that, after enabling WebMIDI in the browser, you need to reboot ChromeOS for a USB MIDI keyboard to be recognized. Once you do, it seems to work fine, but I figured it was worth mentioning if anybody was trying this.

Latency on an Acer c720 Chromebook is nil, by the way. Amazing.

**Comment by cwilso** [comment]
Shouldn't need this with M43+  builds.
