### ISSUE TITLE
Imported resource from origin 'file://' has been blocked from loading by Cross-Origin Resource Sharing policy: Received an invalid response. Origin 'null' is therefore not allowed access. 

### ISSUE THREAD

**Issue by guaka** [cwilso/midi-synth#8]
I'm trying to run this on my local machine.
Getting `Imported resource from origin 'file://' has been blocked from loading by Cross-Origin Resource Sharing policy: Received an invalid response. Origin 'null' is therefore not allowed access.`

This is in Chrome Canary.

**Comment by wgbn** [comment]
But this charging lock prevents the use of polymer a webview application, since a hybrid app files are loaded locally via file:// ?
